"""RELEASE-0001 합성 시험. 사용: python3 -I tests/run_tests.py <RELEASE-0001 폴더> <결과 json>"""
import hashlib, importlib.util, json, os, resource, socket, sys, sysconfig, time
STARTUP_MODS = set(sys.modules)
os.environ.clear()
def _blocked(*a, **k):
    raise OSError("network blocked in RELEASE-0001 tests")
socket.socket.connect = _blocked; socket.socket.connect_ex = _blocked; socket.create_connection = _blocked
ROOT, OUT = os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2])
ALLOWED = sorted({ROOT, sysconfig.get_paths()["stdlib"], sysconfig.get_paths()["platstdlib"]})
OPENS = []
sys.addaudithook(lambda ev, a: OPENS.append((a[0], str(a[1]) if len(a) > 1 else "r"))
                 if ev == "open" and a and isinstance(a[0], str) else None)
def load(n, rel):
    sp = importlib.util.spec_from_file_location(n, os.path.join(ROOT, rel)); m = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(m); return m
A = load("attest", "attest.py"); MZ = load("materialize", os.path.join("tests", "materialize.py"))
FX = json.load(open(os.path.join(ROOT, "fixtures", "fixtures.json"), encoding="utf-8"))
SECRETS = MZ.all_secrets([f["id"] for f in FX["fixtures"]])

def one(at, f):
    d = MZ.materialize(f)
    k = f["kind"]
    if k == "scan":
        got = {"count": at.scan(d)}; raw = got
    elif k == "evaluate":
        raw = at.evaluate(d); got = {"status": raw["status"], "codes": raw["codes"]}
    elif k == "correct":
        new, ch, after, ok = at.correct(d); got = {"changed": ch, "after_count": after, "correctable": ok}; raw = got
    elif k == "correct2":
        n1, c1, a1, _ = at.correct(d); n2, c2, a2, _ = at.correct(n1)
        rest = [l for l in d.split("\n") if "Generated by" not in l] == [l for l in n1.split("\n") if "Generated by" not in l]
        got = {"first_changed": c1, "second_changed": c2, "after_count": a2, "rest_unchanged": rest}; raw = got
    else:
        raw = at.check_receipt(d); got = raw
    return got, raw

def suite(mut=()):
    at = A.Attest(mut); res = {}
    for f in FX["fixtures"]:
        got, raw = one(at, f)
        res[f["id"]] = {"group": f["group"], "got": got, "expected": f["expect"], "pass": got == f["expect"], "raw": raw}
    return res

def view(res):
    return {k: {kk: v[kk] for kk in ("group", "got", "expected", "pass")} for k, v in res.items()}

import re as _re
SID_PARTS = sorted({x.split("_", 1)[1] for x in SECRETS if "_" in x and x.split("_", 1)[1][:3] == "SYN"})
SID_SHAPE = _re.compile(r"session_[A-Za-z0-9]{10,}")
def leaks(res):
    """독립 노출 검사: 합성 값 전체 · 식별자 부분 · session_ 뒤 영숫자 10자 이상 모양 중 하나라도 있으면 셈."""
    blob = json.dumps(res, ensure_ascii=False)
    return sum(1 for s in SECRETS if s in blob) + sum(1 for s in SID_PARTS if s in blob) + len(SID_SHAPE.findall(blob))

def canon(res):
    return hashlib.sha256(json.dumps(view(res), sort_keys=True, ensure_ascii=False).encode()).hexdigest()

t0 = time.time()
r1, r2 = suite(), suite()
mut = {}
for m, must in FX["mutants"].items():
    rm = suite({m}); failed = sorted(k for k, v in rm.items() if not v["pass"]); lk = leaks(rm)
    hit = sorted(set(must) & set(failed)) + (["REDACTION"] if "REDACTION" in must and lk else [])
    mut[m] = {"expected_catchers": must, "caught_by": hit, "caught": bool(hit), "failed_fixtures": failed, "redaction_leaks": lk}
secs = time.time() - t0
inside = lambda p: any(os.path.realpath(p) == a or os.path.realpath(p).startswith(a + os.sep) for a in ALLOWED)
iso = {"allowed_dirs": ["<RELEASE-0001>" if a == ROOT else "<python-stdlib>" for a in ALLOWED],
       "reads_outside_allowed": len({p for p, m in OPENS if not inside(p)}),
       "writes_outside_folder": len({p for p, m in OPENS if any(c in m for c in "wax+") and not os.path.realpath(p).startswith(ROOT)}),
       "new_modules_outside_allowed": sorted(n for n, mm in sys.modules.items() if n not in STARTUP_MODS
                                             and getattr(mm, "__file__", None) and not inside(mm.__file__)),
       "env_cleared": True, "network": "socket connect 차단"}
iso["ok"] = not iso["reads_outside_allowed"] and not iso["writes_outside_folder"] and not iso["new_modules_outside_allowed"]
atk = [k for k, v in r1.items() if v["group"] == "attack"]; alw = [k for k, v in r1.items() if v["group"] == "allow"]
doc = {"task": "RELEASE-0001", "kind": "SYNTHETIC_PRECHECK_ONLY",
       "attest_sha256": hashlib.sha256(open(os.path.join(ROOT, "attest.py"), "rb").read()).hexdigest(),
       "fixtures_sha256": hashlib.sha256(open(os.path.join(ROOT, "fixtures", "fixtures.json"), "rb").read()).hexdigest(),
       "attack_pass": sum(r1[k]["pass"] for k in atk), "attack_total": len(atk),
       "allow_pass": sum(r1[k]["pass"] for k in alw), "allow_total": len(alw), "fixtures": view(r1),
       "redaction_leaks_baseline": leaks(r1),
       "determinism": {"run1": canon(r1), "run2": canon(r2), "same": canon(r1) == canon(r2)},
       "mutants": mut, "mutants_caught": sum(v["caught"] for v in mut.values()), "mutants_total": len(mut),
       "isolation": iso, "budget": {"seconds": round(secs, 3), "max_rss_mb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1)},
       "github_postcheck": "이 파일에 없음 — PR을 연 뒤 PR comment receipt로만 남김"}
doc["synthetic_status"] = "READY" if (doc["attack_pass"] == len(atk) and doc["allow_pass"] == len(alw)
    and doc["mutants_caught"] == len(mut) and doc["determinism"]["same"] and doc["redaction_leaks_baseline"] == 0 and iso["ok"]) else "BLOCKED"
text = json.dumps(doc, ensure_ascii=False, indent=1).replace(ROOT, "<RELEASE-0001>")
assert not any(s in text for s in SECRETS) and not any(s in text for s in SID_PARTS) and not SID_SHAPE.search(text)
open(OUT, "w", encoding="utf-8").write(text)
print(doc["synthetic_status"], "attack", doc["attack_pass"], "/", len(atk), "allow", doc["allow_pass"], "/", len(alw),
      "mut", doc["mutants_caught"], "/", len(mut), "det", doc["determinism"]["same"], "iso", iso["ok"], doc["budget"])
for k, v in r1.items():
    if not v["pass"]:
        print(" FAIL", k, v["got"], "기대", v["expected"])
for k, v in mut.items():
    if not v["caught"]:
        print(" MUT-MISS", k, v["failed_fixtures"])
