"""RELEASE-0001 사후 공개상태 증명 도우미(표준 라이브러리만, 규칙은 PREREG-LOCK 1장).
매치된 문자열은 어떤 함수도 돌려주지 않습니다(개수 · 코드 · SHA만). mutations는 변이 시험에서만 씁니다."""
import re

_HOST = re.escape("claude" + ".ai") + r"/code/" + "session" + "_"
URL_RE = re.compile(_HOST + r"[A-Za-z0-9]{6,}", re.I)
URL_RE_CS = re.compile(_HOST + r"[A-Za-z0-9]{6,}")
TRAILER_RE = re.compile(r"^\s*claude-session\s*:", re.I | re.M)
GENERIC_FOOTER = "_Generated by Claude Code_"
RECEIPT_KEYS = ("task_id", "result_pr", "head_sha", "checked_at_kst", "body_private_session_count",
                "commit_private_session_count", "body_corrected", "branch_commit_after_open", "status")


class Attest:
    def __init__(self, mutations=()):
        self.mut = set(mutations)
        self.url = URL_RE_CS if "N7" in self.mut else URL_RE

    def scan(self, text):
        if not text:
            return 0
        n = 0
        for line in text.splitlines():
            u = len(self.url.findall(line))
            n += u if u else (1 if TRAILER_RE.match(line) else 0)
        return n

    def correct(self, body):
        """footer 줄의 세션 주소만 일반 표기로. (새 본문, 바뀜 여부, 보정 뒤 개수, 보정 가능 여부)"""
        out, changed = [], False
        for line in (body or "").split("\n"):
            if self.url.search(line) and "generated by" in line.lower():
                if line != GENERIC_FOOTER:
                    changed = True
                out.append(GENERIC_FOOTER)
            else:
                out.append(line)
        new = "\n".join(out)
        after = self.scan(new)
        return new, changed, after, after == 0

    def evaluate(self, s):
        codes = []
        if not s.get("fetched_after_open") or s.get("body") is None:
            codes.append("POSTCHECK_MISSING")
        elif s.get("postcheck_source") != "github" and "N4" not in self.mut:
            codes.append("POSTCHECK_NOT_GITHUB")
        body_n = 0 if "N1" in self.mut else self.scan(s.get("body"))
        commit_n = 0 if "N2" in self.mut else sum(self.scan(c.get("message")) for c in s.get("commits") or [])
        if body_n:
            codes.append("PRIVATE_SESSION_METADATA:body")
        if commit_n:
            codes.append("PRIVATE_SESSION_METADATA:commit")
        if "N3" not in self.mut and s.get("head_sha") != s.get("expected_head"):
            codes.append("IMMUTABILITY_FAIL:head")
        after_open = len(s.get("commits") or []) > int(s.get("commits_at_open") or 0)
        if after_open:
            codes.append("IMMUTABILITY_FAIL:commit_after_open")
        if "N6" not in self.mut and not s.get("comment_found"):
            codes.append("COMMENT_NOT_CONFIRMED")
        out = {"status": "BLOCKED" if codes else "READY", "codes": sorted(codes), "body_private_session_count": body_n,
               "commit_private_session_count": commit_n, "branch_commit_after_open": after_open}
        if "N5" in self.mut:                         # 변이: 매치값을 결과에 넣음(노출)
            out["matched"] = self.url.findall(s.get("body") or "")
        return out

    def check_receipt(self, r):
        codes = []
        if set(r) - set(RECEIPT_KEYS):
            codes.append("RECEIPT_EXTRA_FIELD")
        if set(RECEIPT_KEYS) - set(r):
            codes.append("RECEIPT_MISSING_FIELD")
        if any(self.scan(str(v)) for v in r.values()):
            codes.append("RECEIPT_LEAK")
        return {"valid": not codes, "codes": sorted(codes)}


def receipt_text(r):
    """comment 본문: 9키를 key: value 줄로, 끝에 일반 표기."""
    # 끝 줄은 세션 없는 일반 출처 표기(댓글 규칙의 표준 footer)
    lines = ["RELEASE-0001 post-publish receipt"] + [f"- {k}: {r[k]}" for k in RECEIPT_KEYS] + [
        "", "---", "_Generated by [Claude Code](https://claude.ai/code)_"]
    return "\n".join(lines)
