"""RELEASE-0001 합성 fixture(자리표시자만). {{URL}} = 합성 비공개 세션 주소, {{HOSTUP}} = 대문자 호스트 변형,
{{TRAILER}} = 합성 세션 trailer 줄. 값은 tests/materialize.py가 메모리에서 만듦.
사용: python3 -I fixtures/make_fixtures.py fixtures/fixtures.json"""
import json, sys
H1, H2 = "a" * 40, "b" * 40
def snap(**kw):
    s = {"pr": 999, "fetched_after_open": True, "postcheck_source": "github", "body": "본문\n\n_Generated by Claude Code_",
         "head_sha": H1, "expected_head": H1, "commits": [{"sha": H1, "message": "결과 커밋"}], "commits_at_open": 1,
         "comment_found": True}
    s.update(kw); return s
F = []
def f(i, kind, data, expect, group):
    F.append({"id": i, "group": group, "kind": kind, "data": data, "expect": expect})
# 공격 18
f("X01", "scan", "본문\n\n_Generated by [Claude Code]({{URL}})_", {"count": 1}, "attack")
f("X02", "scan", "본문\n{{URL}}", {"count": 1}, "attack")
f("X03", "scan", "참고 ({{URL}}) 끝", {"count": 1}, "attack")
f("X04", "scan", "본문\n\n_Generated by Claude Code — {{URL}}_", {"count": 1}, "attack")
f("X05", "scan", "앞 {{URL}}\n가운데\n뒤 {{URL}}", {"count": 2}, "attack")
f("X06", "scan", "제목\n\n본문\n\n{{TRAILER}}", {"count": 1}, "attack")
f("X07", "scan", "결과 {{URL}} 제출", {"count": 1}, "attack")
f("X08", "evaluate", snap(body="본문\n\n_Generated by [Claude Code]({{URL}})_"),
  {"status": "BLOCKED", "codes": ["PRIVATE_SESSION_METADATA:body"]}, "attack")
f("X09", "evaluate", snap(head_sha=H2), {"status": "BLOCKED", "codes": ["IMMUTABILITY_FAIL:head"]}, "attack")
f("X10", "evaluate", snap(commits=[{"sha": H1, "message": "결과 커밋"}, {"sha": H2, "message": "뒤 커밋"}]),
  {"status": "BLOCKED", "codes": ["IMMUTABILITY_FAIL:commit_after_open"]}, "attack")
f("X11", "correct", "앞 문단 {{URL}} 가운데\n\n_Generated by Claude Code_",
  {"changed": False, "after_count": 1, "correctable": False}, "attack")
f("X12", "evaluate", snap(postcheck_source="local"), {"status": "BLOCKED", "codes": ["POSTCHECK_NOT_GITHUB"]}, "attack")
f("X13", "evaluate", snap(fetched_after_open=False, body=None), {"status": "BLOCKED", "codes": ["POSTCHECK_MISSING"]}, "attack")
f("X14", "receipt", {"task_id": "T", "result_pr": 1, "head_sha": H1, "checked_at_kst": "2026-10-08T09:00:00+09:00",
                     "body_private_session_count": 0, "commit_private_session_count": 0, "body_corrected": False,
                     "branch_commit_after_open": False, "status": "READY", "note": "{{URL}}"},
  {"valid": False, "codes": ["RECEIPT_EXTRA_FIELD", "RECEIPT_LEAK"]}, "attack")
f("X15", "receipt", {"task_id": "T", "result_pr": 1, "head_sha": H1, "checked_at_kst": "2026-10-08T09:00:00+09:00",
                     "body_private_session_count": 0, "commit_private_session_count": 0, "body_corrected": False,
                     "branch_commit_after_open": False, "status": "READY", "body": "본문"},
  {"valid": False, "codes": ["RECEIPT_EXTRA_FIELD"]}, "attack")
f("X16", "evaluate", snap(comment_found=False), {"status": "BLOCKED", "codes": ["COMMENT_NOT_CONFIRMED"]}, "attack")
f("X17", "evaluate", snap(commits=[{"sha": H1, "message": "결과 커밋\n\n{{TRAILER}}"}]),
  {"status": "BLOCKED", "codes": ["PRIVATE_SESSION_METADATA:commit"]}, "attack")
f("X18", "scan", "본문 {{HOSTUP}}", {"count": 1}, "attack")
# 허용 9
f("Y01", "scan", "본문\n\n_Generated by Claude Code_", {"count": 0}, "allow")
f("Y02", "scan", "generic pattern: `claude.ai/code/session_` 뒤에 식별자가 붙은 모양을 막는다", {"count": 0}, "allow")
f("Y03", "scan", "RELEASE-0001: 결과 커밋\n\nCo-Authored-By: Claude <noreply@anthropic.com>", {"count": 0}, "allow")
f("Y04", "evaluate", snap(), {"status": "READY", "codes": []}, "allow")
f("Y05", "evaluate", snap(commits=[{"sha": "c" * 40, "message": "잠금"}, {"sha": H1, "message": "결과"}], commits_at_open=2),
  {"status": "READY", "codes": []}, "allow")
f("Y06", "receipt", {"task_id": "T", "result_pr": 1, "head_sha": H1, "checked_at_kst": "2026-10-08T09:00:00+09:00",
                     "body_private_session_count": 0, "commit_private_session_count": 0, "body_corrected": True,
                     "branch_commit_after_open": False, "status": "READY"}, {"valid": True, "codes": []}, "allow")
f("Y07", "correct", "본문\n\n_Generated by Claude Code_", {"changed": False, "after_count": 0, "correctable": True}, "allow")
f("Y08", "correct2", "본문 첫 줄\n\n_Generated by [Claude Code]({{URL}})_",
  {"first_changed": True, "second_changed": False, "after_count": 0, "rest_unchanged": True}, "allow")
f("Y09", "scan", "링크 https://claude.ai/code 참고", {"count": 0}, "allow")
M = {"N1": ["X08"], "N2": ["X17"], "N3": ["X09"], "N4": ["X12"], "N5": ["REDACTION"], "N6": ["X16"], "N7": ["X18"]}
json.dump({"task": "RELEASE-0001", "note": "자리표시자만. 값은 시험 때 메모리에서 만듦", "fixtures": F, "mutants": M},
          open(sys.argv[1], "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(sum(x["group"] == "attack" for x in F), sum(x["group"] == "allow" for x in F), len(M))
